import { SITE_DOMAIN } from "@/lib/site-config"

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background text-foreground overflow-x-hidden">
      <main className="container mx-auto px-4 py-16">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl md:text-5xl font-bold mb-8 text-slate-900">Terms of Service</h1>
          <div className="prose prose-blue prose-lg max-w-none text-slate-700">
            <p className="lead text-xl text-slate-600 mb-8 border-l-4 border-blue-600 pl-4">
              Welcome to {SITE_DOMAIN}. These Terms of Service govern your use of our website and content.
            </p>
            <h2 className="text-2xl font-bold text-slate-900 mt-12 mb-4">Content Usage and Copyright</h2>
            <p className="mb-6">
              All editorial content, reviews, and images generated by {SITE_DOMAIN} are protected by copyright. You may not reproduce, scrape, or republish our articles without explicit permission and attribution.
            </p>
            <h2 className="text-2xl font-bold text-slate-900 mt-12 mb-4">Affiliate Disclosure</h2>
            <p className="mb-6">
              We earn affiliate commissions from some of the links on our website. This does not affect our editorial independence or the core scores we assign to products. We are not liable for external purchases made through third-party vendors.
            </p>
            <h2 className="text-2xl font-bold text-slate-900 mt-12 mb-4">Liability</h2>
            <p className="mb-6">
              While we strive for accuracy in our comparisons and specifications, {SITE_DOMAIN} is not responsible for pricing errors or changes made by third-party retailers after publication.
            </p>
            <p className="mt-12 text-sm text-slate-500">Last Updated: {new Date().getFullYear()}</p>
          </div>
        </div>
      </main>
    </div>
  )
}
